### ISSUE TITLE
Bot Goes Online but no messages are being relayed at all.

### ISSUE THREAD

**Issue by aaronhnsy** [MiraWaNeko/DiscordIntegration#107]
### Base informations
1.7.10

2.30

{
  "discord": {
    "token": "CORRECT TOKEN IS HERE",
    "ignoresBots": true,
    "allowLinking": true,
    "ignoresUsers": [],
    "channels": {
      "generic": {
        "commandPrefix": "!",
        "canExecuteCommands": true,
        "stripMinecraftCodes": true,
        "allowDMCommands": true,
        "relayChat": true,
        "messages": {
          "chatMessage": "[{USER}] {MESSAGE}"
        },
        "commands": []
      },
      "channels": {}
    }
  },
  "minecraft": {
    "dimensions": {
      "generic": {
        "ignoreFakePlayerChat": true,
        "relaySayCommand": true,
        "relayMeCommand": true,
        "canMentionEveryone": false,
        "canMentionHere": false,
        "messageIgnoreRegex": [],
        "relayServerStart": true,
        "relayServerStop": true,
        "relayServerCrash": true,
        "chatPrefix": "",
        "canMentionUsers": true,
        "canMentionRoles": true,
        "discordChannel": [361566799772254208],
        "relayAchievements": true,
        "relayChat": true,
        "relayCommands": false,
        "relayPlayerJoin": true,
        "relayPlayerLeave": true,
        "relayPlayerDeath": true,
        "messages": {
          "chatMessage": {
            "normal": "**[{USER}]** {MESSAGE}",
            "webhook": "{MESSAGE}"
          },
          "command": {
            "normal": "**[{USER}]** executed **{COMMAND} {ARGUMENTS}**",
            "webhook": "*executed **{COMMAND} {ARGUMENTS}***"
          },
          "playerJoin": {
            "normal": "**{USER}** just joined the server!",
            "webhook": "*Joined the server!*"
          },
          "playerLeave": {
            "normal": "**{USER}** just left the server!",
            "webhook": "*Left the server!*"
          },
          "playerDeath": {
            "normal": "**{USER}** just died due to {REASON}!",
            "webhook": "*{REASON}*"
          },
          "achievement": {
            "normal": "**{USER}** just gained the achievement **{ACHIEVEMENT}**!\n*{DESCRIPTION}*",
            "webhook": "*Gained the achievement **{ACHIEVEMENT}**!\n{DESCRIPTION}*"
          },
          "serverStart": "Server started!",
          "serverStop": "Server stopped!",
          "serverCrash": "Server crash detected!"
        }
      },
      "dimensions": {}
    },
    "integrations": {
      "dynmapEnabled": true
    }
  },
  "imc": {
    "enabled": true,
    "mode": "whitelist",
    "list": []
  }
}

Please Dont Close this Issue as im a noob and may need more help then someone just saying your forgot a letter

**Comment by andrelec1** [comment]
You need to put channels id in discord section, and you need to put dimension id  
`{
"discord": {
"token": "CORRECT TOKEN IS HERE",
"ignoresBots": true,
"allowLinking": true,
"ignoresUsers": [],
"channels": {
"generic": {
"commandPrefix": "!",
"canExecuteCommands": true,
"stripMinecraftCodes": true,
"allowDMCommands": true,
"relayChat": true,
"messages": {
"chatMessage": "[{USER}] {MESSAGE}"
},
"commands": []
},
"channels": {
"PUTTHEIDDISCORDHERE":{}
}
}
},
"minecraft": {
"dimensions": {
"generic": {
"ignoreFakePlayerChat": true,
"relaySayCommand": true,
"relayMeCommand": true,
"canMentionEveryone": false,
"canMentionHere": false,
"messageIgnoreRegex": [],
"relayServerStart": true,
"relayServerStop": true,
"relayServerCrash": true,
"chatPrefix": "",
"canMentionUsers": true,
"canMentionRoles": true,
"discordChannel": [361566799772254208],
"relayAchievements": true,
"relayChat": true,
"relayCommands": false,
"relayPlayerJoin": true,
"relayPlayerLeave": true,
"relayPlayerDeath": true,
"messages": {
"chatMessage": {
"normal": "[{USER}] {MESSAGE}",
"webhook": "{MESSAGE}"
},
"command": {
"normal": "[{USER}] executed {COMMAND} {ARGUMENTS}",
"webhook": "executed {COMMAND} {ARGUMENTS}"
},
"playerJoin": {
"normal": "{USER} just joined the server!",
"webhook": "Joined the server!"
},
"playerLeave": {
"normal": "{USER} just left the server!",
"webhook": "Left the server!"
},
"playerDeath": {
"normal": "{USER} just died due to {REASON}!",
"webhook": "{REASON}"
},
"achievement": {
"normal": "{USER} just gained the achievement {ACHIEVEMENT}!\n*{DESCRIPTION}*",
"webhook": "Gained the achievement {ACHIEVEMENT}!\n{DESCRIPTION}"
},
"serverStart": "Server started!",
"serverStop": "Server stopped!",
"serverCrash": "Server crash detected!"
}
},
"dimensions": {
"0":{}
}
},
"integrations": {
"dynmapEnabled": true
}
},
"imc": {
"enabled": true,
"mode": "whitelist",
"list": []
}
}

`

**Comment by aaronhnsy** [comment]
@andrelec1 what discord id do i put
the one of the server?

**Comment by MyNameBeMrRandom** [comment]
or channel

**Comment by aaronhnsy** [comment]
@andrelec1

**Comment by aaronhnsy** [comment]
bump

**Comment by andrelec1** [comment]
361566799772254208 => same channel id

**Comment by aaronhnsy** [comment]
Ok so i found a website that will genearte this config https://wip.discordintegration.net/config/generator
it worked the first time but now its broken and wont relay chat from minecraft to discord :( @andrelec1

**Comment by aaronhnsy** [comment]
https://pastebin.com/0jD964Fz

**Comment by andrelec1** [comment]
"discordChannel": [361566799772254208]
 "dimensions": {
		"0": {}
	  }

**Comment by aaronhnsy** [comment]
look that really doesnt help me

**Comment by andrelec1** [comment]
Use your brain please ... !!!!

https://pastebin.com/dPt51xy1

**Comment by aaronhnsy** [comment]
that didnt work @andrelec1

**Comment by aaronhnsy** [comment]
the message from discord i seen in minecraft

**Comment by aaronhnsy** [comment]
but msg from minecrafft doesnt show in discord

**Comment by aaronhnsy** [comment]
https://discord.gg/gNreV5 join my discord and youll see

**Comment by aaronhnsy** [comment]
@andrelec1

**Comment by Mijago** [comment]
Closed due to inactivity.

We will update the wiki and config in the future, such issues should be no problem then.
