### ISSUE TITLE
Message customization does not seem to work

### ISSUE THREAD

**Issue by dannydjdk** [MiraWaNeko/DiscordIntegration#139]
Customization of messages is being ignored. For instance, I changed the "playerDeath" message to "**{USER}** {REASON}", but it still print the default "**{USER}** had died due to {REASON}" in Discord. I've changed all the messages to custom messages, but all are printed as default.
All other settings in the config file seem to be working, and the mod is otherwise working beautifully.

**Minecraft version:** 1.12.2
**DiscordIntegration version:** 2.3.0
**Server type and version:** Forge 14.23.2.2611
**Link to pastebin with (censored) config:** https://pastebin.com/rhNZMXNj

### Expected behavior
When a player is killed by a zombie, it's expected to print "<player> was slain by Zombie" in Discord chat per my config setting.

### Actual behavior
When a player is killed by a zombie, it prints "<player> just died due to was slain by Zombie!" as is the default message.

**Comment by dannydjdk** [comment]
I hate to make troubleshooting this even more difficult, but I'm finding that the behavior is not consistent. Every once in a while it will print the custom messages from my configs. It seems to be player based. For instance, for a while, whenever one particular player joins the game, my custom message appears, which is simply "**player1** joined!", but when anyone else joins it prints the default message, "**player2** just joined the server!" Then a little while later, it will print the default message again for player1. I haven't discovered a pattern yet.

**Comment by Ricket** [comment]
Does it have to do with which dimension the player is in when they join, die, etc?

I notice that there is dimension-specific configuration, with a "generic" dimension as a fallback. I also notice that your config has:
```
      "dimensions": {
        "-1": {
 
        },
        "0": {
 
        },
        "1": {
 
        }
      }
```
while mine only has `"dimensions": {}`

Maybe that makes a difference?

Overworld, nether, and end are 0, -1, 1 respectively. If you have mods with other dimensions (RFtools dimensions, twilight forest, mining dimension, etc) then compare what happens when you do things in the different dimensions and see if that solves the mystery.

**Comment by dannydjdk** [comment]
@Ricket, Yes, that was it! Thank you!
I misunderstood how the dimension config works.

**Comment by Ricket** [comment]
@Chikachi You may want to fix this behavior, or update the default config wiki page (which also has those blank dimension sections), so that others don't trip over it.
