### ISSUE TITLE
DiscordIntegration Not Working In MC 1.10.2?

### ISSUE THREAD

**Issue by janagyjr** [MiraWaNeko/DiscordIntegration#175]
### Base informations
**Minecraft version:**
1.10.2

**DiscordIntegration version:**
3.0.4

**Server type and version:** *Forge/Spigot/Sponge*
Forge 12.18.3.2281

**Link to pastebin with (censored) config:** *Optional*
https://gist.github.com/janagyjr/7f709db74ce3233b919f0a232664fb45

### Expected behavior
Bot sends chat to/from Discord and MC

### Actual behavior
Nothing

### Steps to reproduce
Load pack via MultiMC
Add in DiscordIntegration
Launch pack
???
Profit! (mabye)

**Comment by janagyjr** [comment]
The [logfile](https://gist.github.com/janagyjr/77fe62ba7eaa71911a776ab0eaabe02d) from launching the pack (I'm having this issue in SkyFactory 3 (1.10.2), FoolCraft 3 (1.12.2) and assuming other packs/versions as well.

**Comment by jusvit** [comment]
@janagyjr  

## Case 1: Is your token correct?
Ensure you got the token from the bot, not the initial page, please follow carefully the steps of this guide: [How to get token](https://github.com/Chikachi/DiscordIntegration/wiki/How-to-get-a-token-and-channel-ID-for-Discord)

From your configs and logs I can't see anything obviously wrong.

## Case 2: Is it installed?
This probably is useless since the mod has already generated the configs, therefore is running. However, are you able to run discord commands in-game? Try doing /discord config reload and see if you get a response. If you don't, you haven't installed the mod properly.

**Comment by janagyjr** [comment]
Sorry I couldn't answer this soon enough for you, I understand your busy. I will get to working on checking that out asap but by "install" I assume you mean "place in the mods folder and launch Minecraft". Not sure how you can not do that properly. The rest is all configs. I'll check the token, but I'm using the same settings (tokens, id's for the specific room, etc.) in the 1.7.10 version with no issue.

**Comment by jusvit** [comment]
> Sorry I couldn't answer this soon enough for you, I understand your busy. I will get to working on checking that out asap but by "install" I assume you mean "place in the mods folder and launch Minecraft". Not sure how you can not do that properly. The rest is all configs. I'll check the token, but I'm using the same settings (tokens, id's for the specific room, etc.) in the 1.7.10 version with no issue.

Sorry, closing the issue was only to clear some of the old issues, which are most probably abandoned. I'll reopen once you've doubled checked the token.

**Comment by janagyjr** [comment]
I get no response from the mod and I do have the proper token. What version of forge is required for DiscordIntegration-mc1.10.2-3.0.4?
